[traefik-scrapers]
enabled   = true
filter    = traefik-scrapers
logpath   = /var/lib/docker/volumes/traefik-logs/_data/access.log
backend   = polling
banaction = docker-user
maxretry  = 2
findtime  = 10m
bantime   = 24h
